[package]
name = "simplex_method_bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simplex_method = "0.1.0"
ndarray = "0.15.3"
env_logger = "0.9.0"
